import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
// Execute the actual endpoint with only its external email binding replaced.
const transpile=s=>stripTypeScriptTypes(s);
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const helpers=url(transpile(fs.readFileSync(new URL('../src/lib/form-utils.ts',import.meta.url),'utf8')));
const source=fs.readFileSync(new URL('../src/pages/api/contact.ts',import.meta.url),'utf8').replace("'../../lib/form-utils'",JSON.stringify(helpers)).replace("import { env } from 'cloudflare:workers';","const env = globalThis.__step2EmailEnv;").replaceAll('import.meta.env.','env.');
const options=[...fs.readFileSync(new URL('../src/components/sections/ContactFormSection.astro',import.meta.url),'utf8').split('const projectTypes = [')[1].split('];')[0].matchAll(/value: "([^"]+)"/g)].map(m=>m[1]);
test('All six current contact choices reach email payload without a real send',async()=>{const sent=[];globalThis.__step2EmailEnv={EMAIL:{send:async p=>sent.push(p)}};const {POST}=await import(url(transpile(source)));assert.deepEqual(options,['custom-software-development','erp-solutions','business-automation','ai-automation-agents','cloud-devops','other']);for(const [i,option]of options.entries()){const form=new FormData();for(const[k,v]of Object.entries({name:'Step 2 test',email:'test@example.invalid',message:'Local test only',project_type:option}))form.set(k,v);const r=await POST({request:new Request('http://localhost/api/contact',{method:'POST',headers:{'cf-connecting-ip':'192.0.2.'+i},body:form})});assert.equal(r.status,200);assert.equal((await r.json()).success,true);assert.ok(sent[i].text.includes('Project Type: '+option));}delete globalThis.__step2EmailEnv;});
test('Contact validation and send failure remain recoverable',async()=>{globalThis.__step2EmailEnv={EMAIL:{send:async()=>{throw Error('Mock failure')}}};const {POST}=await import(url(transpile(source)+'\n// failure path'));const request=form=>({request:new Request('http://localhost/api/contact',{method:'POST',body:form})});assert.equal((await POST(request(new FormData()))).status,400);const form=new FormData();for(const[k,v]of Object.entries({name:'Test',email:'test@example.invalid',message:'Test',project_type:'cloud-devops'}))form.set(k,v);const r=await POST(request(form));assert.equal(r.status,500);assert.equal((await r.json()).success,false);delete globalThis.__step2EmailEnv;});
