import {test} from 'node:test';import assert from 'node:assert/strict';
import {validateFacts,ORG,COMPANY,POOJAN} from '../scripts/seo/audit-step10b.mjs';
const url='https://kpinfo.tech/insights/erp-for-retail-stores/';
function fixture(){return {url,canonicals:[url],schemas:[{'@graph':[{'@type':'Organization','@id':ORG,name:'KP Infotech',url:'https://kpinfo.tech',sameAs:[COMPANY]},{'@type':'BlogPosting',mainEntityOfPage:{'@type':'WebPage','@id':url},publisher:{'@id':ORG},author:{'@type':'Person',name:'Krupa Joshi',jobTitle:'Founder & Director'}}]}],authorLinks:[],authorText:'Krupa Joshi Founder & Director'};}
test('accepts canonical company and Krupa without invented social identity',()=>assert.deepEqual(validateFacts(fixture()),[]));
test('rejects duplicate and competing company entity architecture',()=>{const f=fixture();f.schemas[0]['@graph'].push({'@type':'LocalBusiness','@id':ORG+'-office'});assert.ok(validateFacts(f).includes('exactly one Organization and no duplicate entity types'));});
for(const profile of ['https://www.instagram.com/kp.infotech/','https://github.com/kp-infotech','https://kpinfotech.co.in','https://kpinfotech.ca','https://kp-infotech.com','https://kpinfosystems.com','https://linkedin.com/company/kp-infotech-solutions'])test('rejects unverified/namesake sameAs '+profile,()=>{const f=fixture();f.schemas[0]['@graph'][0].sameAs.push(profile);assert.ok(validateFacts(f).includes('strict company sameAs'));});
test('rejects Krupa linked to Poojan in schema and visible author block',()=>{const f=fixture();f.schemas[0]['@graph'][1].author.sameAs=[POOJAN];f.authorLinks=[POOJAN];assert.ok(validateFacts(f).includes('Krupa never points to Poojan'));});
test('rejects guessed Krupa replacement',()=>{const f=fixture();f.schemas[0]['@graph'][1].author.sameAs=['https://in.linkedin.com/in/krupa-j-92273819b'];assert.ok(validateFacts(f).includes('Krupa has no guessed social profile'));});
test('requires correct Poojan profile in schema and display',()=>{const f=fixture();f.url='https://kpinfo.tech/insights/angular-vs-react/';f.canonicals=[f.url];const a=f.schemas[0]['@graph'][1];a.mainEntityOfPage['@id']=f.url;a.author={name:'Poojan Patel','@type':'Person',sameAs:[POOJAN]};f.authorLinks=[POOJAN];assert.deepEqual(validateFacts(f),[]);f.authorLinks=[];assert.ok(validateFacts(f).includes('Poojan LinkedIn retained'));});
test('rejects missing/wrong mainEntityOfPage and publisher',()=>{const f=fixture();const a=f.schemas[0]['@graph'][1];delete a.mainEntityOfPage;a.publisher={'@id':ORG+'-other'};assert.ok(validateFacts(f).includes('article mainEntityOfPage'));assert.ok(validateFacts(f).includes('article publisher'));});
test('rejects unverified founding/legal fields and canonical drift',()=>{const f=fixture();Object.assign(f.schemas[0]['@graph'][0],{foundingDate:'2000',legalName:'KP Ltd'});f.canonicals=['https://www.kpinfo.tech/'];assert.ok(validateFacts(f).includes('no unverified Organization fields'));assert.ok(validateFacts(f).includes('self canonical'));});
test('rejects office invitation and directions while retaining required contact routes',()=>{const f=fixture();f.url='https://kpinfo.tech/contact/';f.canonicals=[f.url];f.schemas[0]['@graph'].pop();f.body='Visit Our Office Ahmedabad, Gujarat, India General city map';f.iframes=[];f.forms=['Send Message'];f.links=['mailto:info@kpinfo.tech','tel:+918618279004','https://wa.me/918618279004','https://www.instagram.com/kp.infotech/','https://www.google.com/maps/search/'].map(href=>({href}));assert.ok(validateFacts(f).includes('no visitor office implication'));assert.ok(validateFacts(f).includes('no office directions CTA'));});
test('rejects unsupported Insights experience claims',()=>{const f=fixture();f.url='https://kpinfo.tech/insights/';f.canonicals=[f.url];f.schemas[0]['@graph'].pop();f.intro='Expert perspectives and real-world projects';assert.ok(validateFacts(f).includes('no unsupported experience in hub intro'));});
