import {parse} from 'parse5';
import {readFileSync,writeFileSync} from 'node:fs';
import {attr,txt,inspect} from './audit-step3.mjs';
const input=process.argv[2], output=process.argv[3];
const pages=input==='build'?[...readFileSync('dist/client/sitemap-0.xml','utf8').matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>({url:m[1],status:200,html:readFileSync('dist/client'+new URL(m[1]).pathname+'index.html','utf8')})):JSON.parse(readFileSync(input));
const targets=new Map(pages.map(p=>[new URL(p.url).pathname,{status:p.status,canonical:inspect(p.html,p.url).canonicals[0]}]));
const links=[];
for(const p of pages){function walk(n){if(n.tagName==='a'&&attr(n,'href')){const u=new URL(attr(n,'href'),p.url);if(['kpinfo.tech','www.kpinfo.tech'].includes(u.hostname)){const ancestors=[];for(let a=n;a;a=a.parentNode)ancestors.push(a.tagName+' '+(attr(a,'class')||''));const context=ancestors.join(' | ');const location=/footer/.test(context)?'footer':/navigation|mobile-menu|nav /.test(context)?'navigation':/blog-content__body|service-content/.test(context)?'body':/card|related|service-work/.test(context)?'card':/cta|button/.test(context)?'CTA':'content';links.push({source:new URL(p.url).pathname,destination:u.pathname,href:attr(n,'href'),anchor:attr(n,'aria-label')||txt(n),location,context:context.slice(0,700),...targets.get(u.pathname)});}}for(const c of n.childNodes||[])walk(c);}walk(parse(p.html));}
const pillars=['custom-software-development','erp-software','business-automation','ai-automation-agents','cloud-devops'];
const summary=pillars.map(s=>{const destination='/services/'+s+'/';const a=links.filter(l=>l.destination===destination),local=a.filter(l=>!['navigation','footer'].includes(l.location));return {pillar:s,total:a.length,body:a.filter(l=>l.location==='body').length,contextualPages:new Set(a.filter(l=>l.location==='body').map(l=>l.source)).size,global:a.length-local.length,caseStudy:local.filter(l=>l.source.startsWith('/work/')).length,industry:local.filter(l=>l.source.startsWith('/industries/')).length,insight:local.filter(l=>l.source.startsWith('/insights/')).length,uniquePages:new Set(a.map(l=>l.source)).size,anchors:Object.fromEntries([...new Set(local.map(l=>l.anchor))].map(t=>[t,local.filter(l=>l.anchor===t).length]))};});
function depths(filter){const d={'/':0},queue=['/'];for(const source of queue)for(const l of links.filter(l=>l.source===source&&filter(l)))if(targets.has(l.destination)&&d[l.destination]===undefined){d[l.destination]=d[source]+1;queue.push(l.destination);}return d;}
const errors=links.filter(l=>!l.anchor||!targets.has(l.destination)&&!/^\/(studio|api)\//.test(l.destination));
const result={timestamp:new Date().toISOString(),pages:pages.length,summary,depth:depths(()=>true),contentDepth:depths(l=>!['navigation','footer'].includes(l.location)),links,errors};writeFileSync(output,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({pages:pages.length,summary,errors},null,2));if(errors.length)process.exitCode=1;
