import fs from 'node:fs';
import {parse} from 'parse5';
const phase=process.argv[2]||'baseline',base=process.argv[3]||'https://kpinfo.tech',origin='https://kpinfo.tech';
const out='docs/seo-review/step-11b-evidence';fs.mkdirSync(out,{recursive:true});
const slugs=['business-process-improvement-methods','how-to-choose-erp-system','on-premise-vs-cloud-erp'];
const previous=['/services/business-automation/','/services/erp-software/','/services/erp-software/'];
const excluded={'/business-process-automation-tools/':'/services/business-automation/','/what-is-customised-software/':'/services/custom-software-development/','/data-visualization-best-practices/':'/services/custom-software-development/','/best-ecommerce-platform-for-small-business/':'/industries/retail-ecommerce/'};
const missing=['/how-to-choose-the-right-digital-marketing-channels-for-your-business/','/graphics-design/','/how-to-create-brand-guidelines/','/b-2-b-lead-generation-strategies/','/sample-marketing/','/sample-digital-marketing-strategy/'];
const cache=new Map();async function get(path){const url=new URL(path,base).href;if(!cache.has(url))cache.set(url,(async()=>{let r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(30000)});return {url,status:r.status,location:r.headers.get('location'),robots:r.headers.get('x-robots-tag'),linkHeader:r.headers.get('link'),html:await r.text()};})());return cache.get(url);}
const attr=(n,k)=>n.attrs?.find(a=>a.name===k)?.value;
function inspect(html){let nodes=[];function walk(n){nodes.push(n);for(const c of n.childNodes||[])walk(c);}walk(parse(html));return {canonical:nodes.filter(n=>n.tagName==='link'&&attr(n,'rel')==='canonical').map(n=>attr(n,'href')),h1:nodes.filter(n=>n.tagName==='h1').length,noindex:nodes.some(n=>n.tagName==='meta'&&/^(robots|googlebot)$/i.test(attr(n,'name')||'')&&/noindex|none/i.test(attr(n,'content')||'')),links:nodes.filter(n=>n.tagName==='a').map(n=>attr(n,'href')).filter(Boolean),resources:nodes.filter(n=>['img','script','link','source'].includes(n.tagName)).flatMap(n=>[attr(n,'src'),...(n.tagName==='link'&&/stylesheet|preload|modulepreload/.test(attr(n,'rel')||'')?[attr(n,'href')]:[]),...(attr(n,'srcset')||'').split(',').map(s=>s.trim().split(/\s+/)[0])]).filter(Boolean)};}
const errors=[],redirects=[];const check=(ok,msg)=>{if(!ok)errors.push(msg)};
async function route(path,target){let r=await get(path),hops=[{status:r.status,location:r.location,url:r.url,canonical:inspect(r.html).canonical,linkHeader:r.linkHeader}];for(let i=0;i<5&&r.location;i++){r=await get(new URL(r.location,base).pathname+new URL(r.location,base).search);hops.push({status:r.status,location:r.location,url:r.url});}let final=inspect(r.html);check(hops[0].status===301&&hops.length===2&&r.status===200&&!r.location&&new URL(hops[0].location,base).pathname===target,'redirect '+path);check(!hops[0].canonical.length&&!hops[0].linkHeader,'redirect canonical '+path);check(final.canonical[0]===origin+target&&!final.noindex&&!/noindex|none/i.test(r.robots||''),'final canonical/indexability '+path);redirects.push({path,target,hops,finalStatus:r.status,finalUrl:r.url,canonical:final.canonical,indexable:!final.noindex&&!/noindex|none/i.test(r.robots||'')});}
for(let i=0;i<3;i++){for(const slash of ['/',''])await route('/'+slugs[i]+slash,phase==='baseline'?previous[i]:'/insights/'+slugs[i]+'/');await route('/blogs/'+slugs[i]+'/','/insights/'+slugs[i]+'/');}
for(const [p,t] of Object.entries(excluded))await route(p,t);
const notFound=[];for(const p of missing){const r=await get(p);check(r.status===404&&!r.location,'404 '+p);notFound.push({path:p,status:r.status,location:r.location});}
const sm=await get('/sitemap-0.xml'),urls=[...sm.html.matchAll(/<loc>(.*?)<\/loc>/g)].map(m=>m[1]);check(sm.status===200&&urls.length===56&&new Set(urls).size===56,'56 sitemap');
const pages=[],raw=[],oldLinks=[],resources=new Set();let i=0;await Promise.all(Array.from({length:5},async()=>{while(i<urls.length){const url=urls[i++],r=await get(new URL(url).pathname),p=inspect(r.html);check(r.status===200&&!r.location&&p.canonical.length===1&&p.canonical[0]===url&&!p.noindex&&!/noindex|none/i.test(r.robots||''),'page '+url);for(const href of p.links){let u;try{u=new URL(href,url)}catch{continue}if(u.origin===origin&&slugs.some(s=>u.pathname.replace(/\/$/,'')==='/'+s))oldLinks.push({url,href});}if(slugs.some(s=>url===origin+'/insights/'+s+'/')){check(p.h1===1,'h1 '+url);for(const href of [...p.links,...p.resources]){let u;try{u=new URL(href,url)}catch{continue}if(u.origin===origin)resources.add(u.pathname+u.search);}}pages.push({url,status:r.status,canonical:p.canonical,h1:p.h1,noindex:p.noindex});raw.push({url,status:r.status,html:r.html});}}));
const resourceChecks=[];for(const path of resources){const r=await get(path);check(r.status===200&&!r.location,'destination internal resource '+path);resourceChecks.push({path,status:r.status,location:r.location});}check(oldLinks.length===0,'internal legacy links');
for(const s of slugs){check(urls.includes(origin+'/insights/'+s+'/'),'destination sitemap '+s);check(!urls.includes(origin+'/'+s+'/'),'root sitemap '+s);}
const robots=await get('/robots.txt');check(robots.status===200&&robots.html.includes('Sitemap: '+origin+'/sitemap-index.xml')&&!/^Disallow:\s*\/\s*$/im.test(robots.html),'robots');
fs.writeFileSync('/private/tmp/kp-step11b-'+phase+'-pages.json',JSON.stringify(raw));
fs.writeFileSync(out+'/'+phase+'.json',JSON.stringify({timestamp:new Date().toISOString(),base,redirects,notFound,pages,urls,oldLinks,resourceChecks,robots:{status:robots.status,body:robots.html},errors},null,2));console.log(JSON.stringify({phase,pages:pages.length,redirects:redirects.length,resources:resourceChecks.length,oldLinks:oldLinks.length,errors}));if(errors.length)process.exitCode=1;
