import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import {getMigrationRedirectLocation} from '../../src/worker/migration-redirects.js';
const root=fileURLToPath(new URL('../../',import.meta.url)).replace(/\/$/,'');
const args=Object.fromEntries(process.argv.slice(2).map(arg=>arg.replace(/^--/,'').split(/=(.*)/s).slice(0,2)));
const requestOrigin=args.origin || 'https://kpinfo.tech';
if (!['https://kpinfo.tech','http://127.0.0.1:8789'].includes(requestOrigin)) throw new Error('Unsupported audit origin');
const origin='https://kpinfo.tech';
const decisions=JSON.parse(fs.readFileSync(root+'/tests/fixtures/step-1c-case-study-decisions.json'));
const slugs=['business-process-automation-tools','business-process-improvement-methods','devops-best-practices','how-to-choose-erp-system','on-premise-vs-cloud-erp','what-is-custom-software'];
const expectedWork=decisions.activePublishedSlugs.map(s=>'/work/'+s+'/').sort();
const report={checkedAt:new Date().toISOString(),errors:[],pages:[],redirects:[],removedProjects:[],deadLinks:[],legacyLinks:[]};
const check=(ok,message)=>{if(!ok)report.errors.push(message);};
const attrs=t=>Object.fromEntries([...t.matchAll(/([^\s=<>/"']+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g)].map(m=>[m[1].toLowerCase(),m[2]??m[3]??m[4]]));
const tags=(h,n)=>[...h.matchAll(new RegExp(`<${n}\\b[^>]*>`,'gi'))].map(m=>attrs(m[0]));
const locs=x=>[...x.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1].replaceAll('&amp;','&'));
const request=async(path,method='GET')=>{const r=await fetch(requestOrigin+path,{method,redirect:'manual',signal:AbortSignal.timeout(25000)});return{path,status:r.status,location:r.headers.get('location'),robots:r.headers.get('x-robots-tag'),type:r.headers.get('content-type'),body:await r.text()};};
const graph=v=>Array.isArray(v)?v.flatMap(graph):v&&typeof v==='object'?[v,...Object.values(v).flatMap(graph)]:[];
const sitemap=await request('/sitemap-index.xml');check(sitemap.status===200,'sitemap index status');const children=locs(sitemap.body);check(children.length===1&&children[0]===origin+'/sitemap-0.xml','sitemap index children');
let urls=[];for(const child of children){const u=new URL(child);if(u.origin!==origin){report.errors.push('foreign child sitemap');continue;}const r=await request(u.pathname);check(r.status===200,'child sitemap status');urls.push(...locs(r.body));}
report.sitemapUrls=urls;report.sitemapCount=urls.length;check(new Set(urls).size===urls.length,'duplicate sitemap URLs');
const built=locs(fs.readFileSync(root+'/dist/client/sitemap-0.xml','utf8'));check(JSON.stringify([...urls].sort())===JSON.stringify([...built].sort()),'live sitemap differs from approved build');
for(const slug of slugs)check(urls.includes(origin+'/insights/'+slug+'/'),'missing restored sitemap article '+slug);
const liveWork=urls.filter(u=>new URL(u).pathname.startsWith('/work/')&&new URL(u).pathname!=='/work/').map(u=>new URL(u).pathname).sort();check(JSON.stringify(liveWork)===JSON.stringify(expectedWork),'case study sitemap set');
const linkTargets=new Set();let cursor=0;await Promise.all(Array.from({length:5},async()=>{while(cursor<urls.length){const url=urls[cursor++];try{const u=new URL(url);check(u.origin===origin,'wrong sitemap hostname '+url);if(u.origin!==origin)continue;const r=await request(u.pathname);const canonicals=tags(r.body,'link').filter(a=>a.rel==='canonical').map(a=>a.href);check(r.status===200&&!r.location,'nonfinal sitemap URL '+url+' '+r.status);check(canonicals.length===1&&canonicals[0]===url,'canonical '+url);check(!/\b(noindex|none)\b/i.test(r.robots??''),'robots header '+url);check(!tags(r.body,'meta').some(a=>/^(robots|googlebot)$/i.test(a.name??'')&&/\b(noindex|none)\b/i.test(a.content??'')),'robots meta '+url);
const articleSlug=slugs.find(s=>u.pathname==='/insights/'+s+'/');let articleChecks;
if(articleSlug){const schemas=[...r.body.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].flatMap(m=>{try{return graph(JSON.parse(m[1]));}catch{report.errors.push('invalid JSON-LD '+url);return[];}});articleChecks={blogPosting:schemas.filter(s=>s['@type']==='BlogPosting'&&s.url===url).length,breadcrumbs:schemas.some(s=>s['@type']==='BreadcrumbList'),articleCount:tags(r.body,'article').length,bodyLength:(r.body.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1]??'').replace(/<[^>]*>/g,' ').trim().length};check(articleChecks.blogPosting===1&&articleChecks.breadcrumbs&&articleChecks.articleCount===1&&articleChecks.bodyLength>1000,'article content/schema '+url);}
for(const a of tags(r.body,'a')){if(!a.href)continue;let target;try{target=new URL(a.href,url);}catch{continue;}if(target.origin!==origin)continue;if(/^\/(work|insights)(\/|$)/.test(target.pathname)){linkTargets.add(target.pathname);if(!urls.includes(origin+target.pathname))report.deadLinks.push({source:u.pathname,target:target.pathname});}if(getMigrationRedirectLocation(target) || /^\/(blogs|casestudy)(\/|$)/.test(target.pathname))report.legacyLinks.push({source:u.pathname,target:target.pathname});}
if(u.pathname==='/work/'){const cards=tags(r.body,'a').filter(a=>(a.class??'').split(/\s+/).includes('work-card')).map(a=>new URL(a.href,url).pathname).sort();report.workCards=cards;check(JSON.stringify(cards)===JSON.stringify(expectedWork),'work hub cards');check(!tags(r.body,'div').some(a=>(a.class??'').split(/\s+/).includes('work-card__placeholder')),'placeholder project card');}
report.pages.push({path:u.pathname,status:r.status,canonical:canonicals[0],robots:r.robots,articleChecks});
}catch(e){report.errors.push(url+': '+e.message);}}}));
for(const path of linkTargets)if(!urls.includes(origin+path)){const r=await request(path);check(r.status===200&&!r.location,'internal link not final200 '+path);}
check(report.deadLinks.length===0,'dead/noncanonical internal insight/work links');check(report.legacyLinks.length===0,'legacy internal links');
for(const slug of slugs){const target='/insights/'+slug+'/';for(const source of ['/blogs/'+slug+'/',...(['devops-best-practices','what-is-custom-software'].includes(slug)?['/'+slug+'/']:[])])for(const path of [source,source.slice(0,-1)])for(const method of ['GET','HEAD']){const r=await request(path,method);const u=r.location?new URL(r.location,origin):null;check(r.status===301&&[origin+target,requestOrigin+target].includes(u?.href),'legacy redirect '+method+' '+path);const final=u&&[origin,requestOrigin].includes(u.origin)?await request(u.pathname+u.search,method):null;check(final?.status===200&&!final.location,'legacy final '+method+' '+path);report.redirects.push({source:path,method,status:r.status,location:r.location,finalStatus:final?.status});}}
for(const slug of decisions.removedCaseStudySlugs)for(const path of ['/casestudy/'+slug,'/casestudy/'+slug+'/','/work/'+slug+'/']){const r=await request(path);check(r.status===404&&!r.location&&/text\/html/i.test(r.type??'')&&/Page Not Found/i.test(r.body),'unsupported route '+path+' '+r.status);report.removedProjects.push({path,status:r.status,location:r.location});}
report.sampleMarketing=[];for(const path of ['/sample-digital-marketing-strategy/','/sample-digital-marketing-strategy','/sample-digital-marketing-strategy/?ref=legacy']){const r=await request(path);check(r.status===404&&!r.location&&/Page Not Found/i.test(r.body),'sample marketing '+path+' '+r.status);report.sampleMarketing.push({path,status:r.status,location:r.location});}
const robots=await request('/robots.txt');report.robots={status:robots.status,body:robots.body};check(robots.status===200&&robots.body.includes('Sitemap: '+origin+'/sitemap-index.xml'),'robots sitemap');check(!/^Disallow:\s*\/\s*$/im.test(robots.body),'robots blanket disallow');
report.pages.sort((a,b)=>a.path.localeCompare(b.path));fs.writeFileSync(args.output || '/tmp/kp-step1g-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify({errors:report.errors,sitemapCount:urls.length,pages:report.pages.length,redirectChecks:report.redirects.length,removedProjectChecks:report.removedProjects.length,deadLinks:report.deadLinks.length,legacyLinks:report.legacyLinks.length,sampleMarketing:report.sampleMarketing},null,2));if(report.errors.length)process.exitCode=1;
