import fs from 'node:fs';
import assert from 'node:assert/strict';
import {parse} from 'parse5';
import {pageFacts} from './audit-step10b.mjs';
import {inspect} from './audit-step3.mjs';
export const slugs=['business-process-improvement-methods','how-to-choose-erp-system'];
export function articleFacts(html){const nodes=[];function walk(n){nodes.push(n);for(const c of n.childNodes||[])walk(c);}walk(parse(html));const attr=(n,k)=>n.attrs?.find(a=>a.name===k)?.value;const text=n=>n.nodeName==='#text'?n.value:(n.childNodes||[]).map(text).join(' ');const body=nodes.find(n=>n.tagName==='article'&&attr(n,'class')?.includes('blog-content__body'));assert(body,'Article body exists');const bn=[];function bodyWalk(n){bn.push(n);for(const c of n.childNodes||[])bodyWalk(c);}bodyWalk(body);return {text:text(body).replace(/\s+/g,' ').trim(),tables:bn.filter(n=>n.tagName==='table').map(n=>text(n).replace(/\s+/g,' ').trim()),headings:bn.filter(n=>/^h[23]$/.test(n.tagName)).map(n=>text(n)),lists:bn.filter(n=>n.tagName==='li').map(n=>text(n)),links:bn.filter(n=>n.tagName==='a').map(n=>({href:attr(n,'href'),text:text(n)}))};}
export function quality(html,slug){const f=articleFacts(html);const expected=slug===slugs[0]?['Trigger','Inputs','Owner','Steps','Systems','Handoffs','Approvals','Exceptions','Output','Measure','A process audit checklist','Cycle time','Waiting time','Manual touches','Error/rework rate','Approval delay','Exception volume','Report preparation effort','Number of handoffs','Illustrative example only','not a KP Infotech client project','Improve manually first','Configure an existing system','Automate the workflow','Implement ERP','Build custom software']:['requirements-first','MUST HAVE','SHOULD HAVE','COULD HAVE','NOT REQUIRED NOW','Sales / CRM','Purchasing','Inventory','Finance','Manufacturing','Users / access','Reporting','Integration','Standard support','Configuration needed','Customization needed','Vendor evidence','Implementation risk','Demo checklist','user acceptance testing (UAT)','Data migration questions','Final selection checklist before signing'];for(const s of expected)assert(f.text.includes(s),slug+': '+s);assert(f.tables.length>=(slug===slugs[0]?5:2),'semantic tables');assert(f.lists.length>=20,'reusable lists');assert.doesNotMatch(f.text,/\b\d+(?:\.\d+)?\s*%|[$₹€£]\s*\d|\b(?:certified|certification|Odoo Partner|top[- ]10|best ERP vendor|our research|our clients achieved)\b/i);return f;}
if(process.argv[1]?.endsWith('/audit-step11c.mjs')){
 const phase=process.argv[2]||'build',dir='docs/seo-review/step-11c-evidence/';
 const before=JSON.parse(fs.readFileSync(dir+'baseline-page-facts.json'));
 const cmsAfter=JSON.parse(fs.readFileSync(dir+'cms-after.json'));
 function schemaExpected(schemas,slug){const expected=structuredClone(schemas);function update(v){if(Array.isArray(v))v.forEach(update);else if(v&&typeof v==='object'){if(v['@type']==='BlogPosting')v.dateModified=cmsAfter.find(d=>d.slug.current===slug)._updatedAt;Object.values(v).forEach(update);}}update(expected);return expected;}
 const raw=phase==='build'?before.map(p=>({url:p.url,html:fs.readFileSync('dist/client'+new URL(p.url).pathname+'index.html','utf8')})):JSON.parse(fs.readFileSync('/private/tmp/kp-step11c-production-pages.json'));
 const errors=[],articles=[];for(const b of before){const a=raw.find(p=>p.url===b.url);try{assert(a,'page exists');const f=JSON.parse(JSON.stringify(pageFacts(a.html,a.url))),s=slugs.find(x=>a.url.endsWith('/insights/'+x+'/'));if(!s)assert.deepEqual(f,b.facts,'Unchanged page '+b.url);else {for(const k of Object.keys(b.facts).filter(k=>!['body','links'].includes(k)))assert.deepEqual(f[k],k==='schemas'?schemaExpected(b.facts[k],s):b.facts[k],s+' preserved '+k);const q=quality(a.html,s);for(const l of b.article.links)assert(q.links.some(x=>x.href===l.href),'Preserve prior article link '+l.href);articles.push({slug:s,words:q.text.split(/\s+/).length,tables:q.tables.length,listItems:q.lists.length,headings:q.headings,links:q.links});}const sem=inspect(a.html,a.url);assert(sem.h1.length===1&&!sem.hierarchy.length&&!sem.schemaErrors.length,'semantics');}catch(e){errors.push(e.message);}}
 const result={phase,pages:raw.length,unchangedPages:54,articles,errors};fs.writeFileSync(dir+'quality-'+phase+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));if(errors.length)process.exitCode=1;
}
