import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
export const decode=s=>s.replace(/&(?:amp|quot|apos|lt|gt|#39|#x27);/g,x=>({'&amp;':'&','&quot;':'"','&apos;':"'",'&lt;':'<','&gt;':'>','&#39;':"'",'&#x27;':"'"}[x]));
const text=s=>decode(s.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());
export const attrs=t=>Object.fromEntries([...t.matchAll(/([^\s=<>/"']+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g)].map(m=>[m[1].toLowerCase(),decode(m[2]??m[3]??m[4])]));
const tags=(h,n)=>[...h.matchAll(new RegExp(`<${n}\\b[^>]*>`,'gi'))].map(m=>attrs(m[0]));
export function inspect(html){const head=html.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i)?.[1]||'';const metas=tags(head,'meta');return{schemas:[...html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map(m=>JSON.parse(m[1])),titles:[...head.matchAll(/<title\b[^>]*>([\s\S]*?)<\/title>/gi)].map(m=>text(m[1])),descriptions:metas.filter(m=>m.name==='description').map(m=>m.content),canonicals:tags(head,'link').filter(l=>l.rel==='canonical').map(l=>l.href),h1:[...html.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi)].map(m=>text(m[1])),noindex:metas.some(m=>/^(robots|googlebot)$/i.test(m.name||'')&&/noindex|none/i.test(m.content||'')),meta:Object.fromEntries(metas.map(m=>[m.property||m.name,m.content])),footer:text([...html.matchAll(/<footer\b[^>]*>([\s\S]*?)<\/footer>/gi)].at(-1)?.[1]||''),body:text(html.replace(/<script\b[\s\S]*?<\/script>/gi,''))};}
export const targets=JSON.parse(readFileSync(root+'tests/fixtures/step-2-metadata.json'));
export function validate(result,target,before){const errors=[];const check=(v,m)=>{if(!v)errors.push(target.path+': '+m);};check(result.titles.length===1&&result.titles[0]===target.title,'title');check(result.descriptions.length===1&&result.descriptions[0]===target.description,'description');check(result.canonicals.length===1&&result.canonicals[0]==='https://kpinfo.tech'+target.path,'canonical');check(!result.noindex,'noindex');const nodes=(result.schemas||[]).flatMap(s=>s['@graph']||[s]);check(nodes.some(n=>n['@type']==='Organization'&&n['@id']==='https://kpinfo.tech/#organization'&&n.url==='https://kpinfo.tech'),'organization schema identity');if(target.path.startsWith('/services/')&&target.path!=='/services/')check(nodes.some(n=>n['@type']==='Service'&&n.url==='https://kpinfo.tech'+target.path),'Service schema URL');if(target.path==='/contact/')check(nodes.some(n=>n['@type']==='ContactPage'&&n.url==='https://kpinfo.tech/contact/'),'ContactPage schema URL');check(result.h1.length===1,'H1 count');check(result.h1[0]===(target.path==='/about/'?'Technology Built Around Better Business Operations':target.path==='/services/erp-software/'?'Odoo ERP Implementation & Customization Services':target.path==='/services/business-automation/'?'Business Process Automation Services':target.path==='/services/cloud-devops/'?'Cloud & DevOps Services':target.path==='/services/custom-software-development/'?'Custom Software Development Services':target.path==='/services/ai-automation-agents/'?'AI Agent Development & Automation Services':before.h1[0]),'H1 preservation');for(const platform of ['og','twitter'])for(const [field,expected]of [['title',target.title],['description',target.description],['url','https://kpinfo.tech'+target.path]])check(result.meta[platform+':'+field]===expected,platform+':'+field);check(result.footer.includes('We build custom software, ERP, automation, AI, and cloud systems for growing businesses that need better operations and less manual work.'),'footer positioning');check(!/digital excellence|design & technology studio|premium digital product studio|bring your vision to life|end-to-end digital solutions/i.test(result.body),'legacy positioning');return errors;}
if(process.argv[1]===fileURLToPath(import.meta.url)){
 const origin=process.argv.find(a=>a.startsWith('--origin='))?.slice(9);const output=process.argv.find(a=>a.startsWith('--output='))?.slice(9);
 const before=JSON.parse(readFileSync(root+'docs/seo-review/step-2-evidence/metadata-before.json'));const report={timestamp:new Date().toISOString(),origin:origin||'build',pages:[],errors:[]};
 for(const target of targets){let html,status=200,header='';if(origin){const r=await fetch(origin+target.path,{redirect:'manual'});status=r.status;header=r.headers.get('x-robots-tag')||'';html=await r.text();}else html=readFileSync(root+'dist/client'+target.path+'index.html','utf8');const result=inspect(html);const errors=validate(result,target,before.find(b=>b.path===target.path));if(status!==200||/noindex/i.test(header))errors.push(target.path+': HTTP/indexability');report.errors.push(...errors);report.pages.push({path:target.path,status,...result,body:undefined,errors});}
 if(new Set(report.pages.map(p=>p.titles[0])).size!==targets.length)report.errors.push('Duplicate target titles');if(output)writeFileSync(output,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({pages:report.pages.length,errors:report.errors},null,2));if(report.errors.length)process.exitCode=1;
}
